In [1]:
import matplotlib.pyplot as plt
import numpy as np

π = np.pi

## Canonical Decomposition

$U = k_1 \exp\left(-i \frac{π}{2} (t_x X \otimes X + t_y Y \otimes Y + t_z Z \otimes Z)\right) k_2$

$k_1, k_2$ : single qubit gates
$t_x, t_y, t_z$ : parameterization variables

$X = \begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix}$

$Y = \begin{bmatrix}
0 & -i \\
i & 0 \\
\end{bmatrix}$

$Z = \begin{bmatrix}
1 & 0 \\
0 & -1 \\
\end{bmatrix}$

$X \otimes X = \begin{bmatrix}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
\end{bmatrix}$

$Y \otimes Y = \begin{bmatrix}
0 & 0 & 0 & -i \\
0 & 0 & i & 0 \\
0 & -i & 0 & 0 \\
i & 0 & 0 & 0 \\
\end{bmatrix}$

$Z \otimes Z = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & 1 \\
\end{bmatrix}$








Notation in Vatan, Williams Optimal quantum circuits 2004

$R_Y(\theta) = \begin{bmatrix}
\cos(\frac{\theta}{2}) & -\sin(\frac{\theta}{2}) \\
\sin(\frac{\theta}{2}) & \cos(\frac{\theta}{2})
\end{bmatrix}$

$R_Z(\alpha) = \begin{bmatrix}
e^{-i\frac{\alpha}{2}} & 0 \\
0 & e^{i\frac{\alpha}{2}}
\end{bmatrix}$

$H = \frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix}$

$S = \begin{bmatrix}
1 & 0 \\
0 & i
\end{bmatrix}$

control (if) top, target (then flip) bottom

$CNOT_1 = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{bmatrix}$

target top, control bottom

$CNOT_2 = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0
\end{bmatrix}$

$SWAP = CNOT_1*CNOT_2*CNOT_1 = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}$

Controlled V = $\begin{bmatrix}
I_2 & 0 \\
0 & V \\
\end{bmatrix}$

Magic = $\begin{bmatrix}
1 & i & 0 & 0 \\
0 & 0 & i & 1 \\
0 & 0 & i & -1 \\
1 & -i & 0 & 0
\end{bmatrix}$

### Theorem 1 Rundown
For every $U \in SO(4)$, $U$ in the magic basis $M U M^* \in SU(2) \otimes SU(2)$ 

Show for every $A \otimes B \in SU(2) \otimes SU(2)$, we have $M^*(A \otimes B)M \in SO(4)$

_

$A \in SU(2)$ can be written as a product of $R_z(\alpha)R_y(\theta)R_z(\beta)$

Therefore
$A \otimes B \in SU(2) \otimes SU(2)$ can be written as $V \otimes I_2$ and $I_2 \otimes V$ where $V$ is either $R_y(\theta)$ or $R_z(\alpha)$

**I'm not sure this is okay, my intuition for this step of the proof is that $R_z(\alpha_1)R_y(\theta_1)R_z(\beta_1) \otimes R_z(\alpha_2)R_y(\theta_2)R_z(\beta_2)$ is an arbitrary (about any axis and angle) rotation on qubit one and a separate arbitrary rotation on qubit two and these two separate rotations are equivalent to a conditional rotation on one of the qubits about either the Y or Z axis

if $M^*(V \otimes I_2)M$ and $M^*(I_2 \otimes V)M$ are in $SO(4)$ then the proof is complete (paper argues elementary algebra shows this is the case

$SO(4)$ requirements: determinant = 1, each column/row are unit vectors and orthogonal to each other column/row 


!!! Demonstrates by using the magic basis we can convert a unitary matrix in SO(4) to the product of two matrices in SU(2)!!!

Theorem 2 moves this to include O(4) and U(2)-- determinant = -1

Demonstrates circuit implementations of all two qubit quantum gates in SO(4) using single qubit gates and 2 CNOTS

All designed to motivate move to SU(4) decompositions



### Section 5

$U = A_1 \otimes A_2 \cdot N(\alpha, \beta, \gamma) \cdot A_3 \otimes A_4$ where $A_J \in U(2)$ , $N(\alpha, \beta, \gamma) = \exp\left(i(\alpha \sigma_x \otimes \sigma_x + \beta \sigma_y \otimes \sigma_y + \gamma \sigma_z \otimes \sigma_z)\right)$

if choose $U \in SU(4)$ then choose $A_j \in SU(2)$




$D = M^*NM$

$N(\alpha, \beta, \gamma) = M^*NM$

Can construct a circuit for computing N in terms of this diagonal operation

Can continue to optimize representation into three CNOT gates plus single qubit gates, long explanation using entangling power to argue that this is optimal

Finding gate N, underlying entangling operation leading to an explicit circuit representation of any two qubit unitary operation with at most three CNOTs and 15 y or z single qubit rotations

All of this decomposition stuff, cartan coordinates originates from this magic basis (magic gate has a circuit implementation with S and H gates) and theorem 1-- its ability to decompose SO(4) into the multiplcation of two SO(2) matrices

Now we reach 5 where we transition from SO(4) to SU(4) there's this statement that every gate in U(4) can be written as cartan decomposition and single qubit gates

Then, the cartan decomposition with the use of the magic basis can be rewritten as a diagonal matrix, allowing there to be a circuit implementation of N with first the diagonal matrix gate and changing that into three CNOT gates and single qubit gates

Should have some understanding of why equation 1 exists in the first place-- why the Cartan decomposition is used, why its basis is the product of XX, YY, ZZ

from what I understand from googling and jumping between these papers is that XX YY ZZ were just chosen, i assume there could be another decomposition protocol with XY, YZ etc etc -- corresponding to fsim gate family decomposing gates into two consecutive interactions... maybe I should read more about fsim and make a comparison / understand what approaches to decomposition exist and differences between these approaches.

In [2]:
import numpy as np
import qutip as qt

Bell_00 / $|\Phi^+\rangle$ = $\frac{1}{\sqrt{2}} \left( |00\rangle + |11\rangle \right)$

Bell_01 / $|\Phi^-\rangle$ = $\frac{1}{\sqrt{2}} \left( |00\rangle - |11\rangle \right)$

Bell_10 / $|\Psi^+\rangle$ =  $\frac{1}{\sqrt{2}} \left( |01\rangle + |10\rangle \right)$

Bell_11 / $|\Psi^-\rangle$ =  $\frac{1}{\sqrt{2}} \left( |01\rangle - |10\rangle \right)$

In [3]:
Bell_00 = qt.bell_state('00')
Bell_01 = qt.bell_state('01')
Bell_10 = qt.bell_state('10')
Bell_11 = qt.bell_state('11')

Magic_1 / $|\Phi_1\rangle$ = $|\Phi^+\rangle$

Magic_2 / $|\Phi_2\rangle$ = $-i|\Phi^-\rangle$

Magic_3 / $|\Psi_3\rangle$ = $|\Psi^-\rangle$

Magic_4 / $|\Psi_4\rangle$ = $-i|\Psi^+\rangle$

In [4]:
Magic_1 = Bell_00
Magic_2 = -1j * Bell_01
Magic_3 = Bell_11
Magic_4 = -1j * Bell_10

$U_{AB}$ (arbitrary unitary operating on A and B) $ = $ (can be decomposed into) $ U_A \otimes U_B U_{d} V_A \otimes V_B$

$U_d = e^{-i \vec{\sigma}_A^T d \vec{\sigma}_B}$ where $\vec{\sigma_A} = (\sigma_x, \sigma_y, \sigma_z)$ operating on A and d is a diagonal matrix with elements $ (\alpha_x, \alpha_y, \alpha_z) $

Canonical Decomposition: $U = k_1 \exp\left(-i \frac{π}{2} (t_x X \otimes X + t_y Y \otimes Y + t_z Z \otimes Z)\right) k_2$

# Motivation for this representation

Bennett, Divencenzo Mixed State Entanglement 1996 (thinking in the context of EPR paradox):

In the context of EPP (Entanglement Purification Protocols), Entanglement of a pure state can be quantified as the entropy of formation of either subsystem alone: $E(\Upsilon) = S(\rho_A) = S(\rho_B)$ where $S(\rho) = -\mathrm{Tr}(\rho \log_2 \rho)$ (Von Neumann Entropy) and $\rho_A$ is $\mathrm{Tr}_B \left( | \Upsilon \rangle \langle \Upsilon | \right)$ the reduced density matrix. $E$ ranges from 0 (for a product state) to $\log_2(N)$ for a maximally entangled state of two N-state particles. For the singlet state $|\Psi^-\rangle$, $E=1$

(When pure, entangled states interact with other quantum degrees of freedom they become mixed states and the entanglement of formation becomes more complicated-- don't know how to distill out as much entanglement required to generate the original state from the mixed state in the first place... lots of discussion)

Landed on minimum of entanglement over all ensembles of pure states realizing the mixed state. See page 12 for reasoning. for mixed state $M = \sum_i p_i|\Upsilon_i\rangle\langle\Upsilon_i|, E(M)$ is the minimum $E(\epsilon)$ over ensembles $\epsilon = {p_i, \Upsilon_i}$ making up the mixed state

Return to Wooters, Entanglement of Formation... 1997

We can represent E as an explicit function of $\rho$ (in the case of pure states) with a step in between- the concurrence where $C(\psi)=|\langle\psi|\tilde{\psi}\rangle)$ where $|\tilde{\psi}\rangle = \sigma_y|\psi^*\rangle$ - interpretation in Hill Wooters 1997 that this spin flip operation is equivalent to complex conjugation in the magic basis

This concurrence ranges from 0-1 as entanglement of formation ranges from 0-1 and it increases monotonically-- can be thought of as a measure of entanglement itself. Single state- unchanged by spin flip operation $C=1$, separable pure state such as $|\uparrow\downarrow\rangle$ moved to orthogonal state via spin flip, $C=0$

This reasoning is then extended to mixed states where my understanding becomes more fuzzy (discussion on page 5 of Wooters 1997)

Finally back to Kraus Cirac: in an attempt to find the best input states to maximize entanglement, two important properties stated. statement 1: concurrence of a state is 1 if and only if the state written in the magic basis has real coefficients up to a global phase and the concurrence is 0 iff it's a product state and the coefficients in the magic basis are 0.

Key Statement- Section III unitary operators page 3 in  $U_{AB} =  U_A \otimes U_B U_{d} V_A \otimes V_B$, 

"Note that any measure of entanglement is not changed by local unitary operators. Thus the entanglement created by $U_AB$ is the same as the one Created by $U_D V_A\otimes V_B$ And so the maximal amount of entanglement which can be produced by applying a general unitary, $U_AB$ is the same as the one created by $U_d$."

Additionally Kraus Cirac 2018 Optimal Creation 'proves' in Appendix A that any unitary can be expressed in this way





For certain cases (ie maximal entanglement, three free parameters in $U_d$ are constrained)

## This is an attempt to generate gates via canonical decomposition

motivation: input three parameters into a function, obtain some unitary in a local group

next step-- convert this unitary into points in the Weyl chamber via single qubit gates... this motivation is not fully thought out but it seems like a decent first step.

In [18]:
π = np.pi

xx = qt.Qobj(np.kron(qt.sigmax(), qt.sigmax()))
yy = qt.Qobj(np.kron(qt.sigmay(), qt.sigmay()))
zz = qt.Qobj(np.kron(qt.sigmaz(), qt.sigmaz()))

xy = qt.Qobj(np.kron(qt.sigmax(), qt.sigmay()))
yx = qt.Qobj(np.kron(qt.sigmay(), qt.sigmax()))
xz = qt.Qobj(np.kron(qt.sigmax(), qt.sigmaz()))
zx = qt.Qobj(np.kron(qt.sigmaz(), qt.sigmax()))
yz = qt.Qobj(np.kron(qt.sigmay(), qt.sigmaz()))
zy = qt.Qobj(np.kron(qt.sigmaz(), qt.sigmay()))

In [19]:
def can_decomp(tx, ty, tz):
    xx = qt.Qobj(np.kron(qt.sigmax(), qt.sigmax()))
    yy = qt.Qobj(np.kron(qt.sigmay(), qt.sigmay()))
    zz = qt.Qobj(np.kron(qt.sigmaz(), qt.sigmaz()))

    return ((tx*xx + ty*yy + tz*zz)*(-1j*π/2)).expm()

In [22]:
tx = 1/2
ty = 1/2
tz = 0

can_decomp(tx, ty, tz)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

In [10]:
π/2

1.5707963267948966

In [11]:
xx

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

In [12]:
yy

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]]

In [24]:
can_decomp(-0.5, 0, 0) #Mølmer-Sørensen gate (MS)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.70710678j]
 [0.        +0.j         0.70710678+0.j         0.        +0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.70710678j 0.70710678+0.j
  0.        +0.j        ]
 [0.        +0.70710678j 0.        +0.j         0.        +0.j
  0.70710678+0.j        ]]

## What is it about all of these above gates (before applying 12 DOF single qubit gates) (touching all the local equivalence classes) that let them be described with only three parameters?

I wonder with a different basis (not xx, yy, zz) there are different "natural gates" in each local equivalence class that don't immediately require single qubit gates****

## Commutations

can separate do that one property

In [18]:
xx*yy == yy*xx

True

In [60]:
generators = [xx, yy, zz, xy, yx, xz, zx, yz, zy]
commutators = []
for i in generators:
    for j in generators:
        t1 = (i*j)
        t2 = (j*i)
        commutators.append(t1==t2)
    commutators.append('_')

In [61]:
(xx*yz) - (yz*xx)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

| **Pauli Matrix Products** | **XX** | **YY** | **ZZ** | **XY** | **YX** | **XZ** | **ZX** | **YZ** | **ZY** |
|--------------------------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| **XX**                   |   0    |   0    |   0    |    non   |    non   |   non    |   non    |   0    |    0   |
| **YY**                   |   0    |   0    |   0    |    non   |    non   |   0    |   0    |    non   |    non   |
| **ZZ**                   |   0    |   0    |   0    |    0   |    0   |   non    |   non    |   non    |   non    |
| **XY**                   |   non    |   non    |   0    |   0    |    0   |   non    |   0    |   0    |   non    |
| **YX**                   |   non    |   non    |   0    |   0    |    0   |    0   |    non   |    non   |   0    |
| **XZ**                   |   non    |    0   |    non   |   non    |   0    |   0    |   0    |    non   |   0    |
| **ZX**                   |   non    |    0   |    non   |    0   |    non   |   0    |   0    |   0    |    non   |
| **YZ**                   |   0    |    non   |   non    |   0    |   non    |   non    |    0   |   0    |   0    |
| **ZY**                   |   0    |   non    |   non    |   non    |   0    |   0    |   non    |   0    |    0   |


In [67]:
yx*xz - xz*yx   #**** this is the only unintuitive case

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [55]:
xx*zy - zy*xx

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [26]:
(xx*yy) - (yy*xx)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [28]:
(xy*xz) - (xz*xy)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.+0.j 0.+2.j 0.+0.j 0.+0.j]
 [0.+2.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+2.j]
 [0.+0.j 0.+0.j 0.+2.j 0.+0.j]]

In [21]:
yx

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]

In [60]:
yy*xx

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

In [61]:
xx*zz

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]]

In [62]:
zz*xx

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]]

In [63]:
yy*zz

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]]

## Next Step:

Converting between locally equivalent gates via single qubit gates, given an arbitrary unitary decompose into tx, ty, tz? - understand weyl chambers numerically as opposed to completely mathematically-- , use randomizers and statistics to be more convinced of completeness and other properties

If I have a function to determine all of these parameters.