In [73]:
import qutip as qt
import numpy as np

In [74]:
num_basis = 2
π = np.pi

## Beamsplitter Gate

In [101]:
a = qt.tensor(qt.destroy(num_basis), qt.qeye(num_basis))
adag = a.dag() 
b = qt.tensor(qt.qeye(num_basis), qt.destroy(num_basis))
bdag = b.dag() 

g_state = qt.basis(num_basis, 0)
e_state = qt.basis(num_basis, 1)

gg = qt.tensor(g_state, g_state)
ge = qt.tensor(g_state, e_state)
eg = qt.tensor(e_state, g_state)
ee = qt.tensor(e_state, e_state)

B = ((adag*b-a*bdag)*π/4).expm()

In [106]:
ge

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [107]:
B*ge #ge+eg

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

In [108]:
B*eg #-ge+eg

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [-0.70710678]
 [ 0.70710678]
 [ 0.        ]]

In [111]:
B.dag()*ge #ge-eg

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

In [85]:
B.dag()*eg #ge+eg

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

In [88]:
adag*b

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]

In [89]:
a*bdag

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

## Phase Modulator

In [69]:
a = qt.destroy(num_basis)
adag = a.dag()
g = g_state
e = e_state

S = 